### PR TITLE
1-MagentoSetup:upload files

### PR DESCRIPTION
**Pull request by alexandr-tg**

### CODE REVIEW

**Comment by alexandr-tg** [comment]
[Lesson1-1](https://trello.com/c/EyIwUD5N/7-lesson1-1)

**Comment by epolish** [comment]
Branch name should be feature/Lesson1-1-MagentoSetup (for the future)

**Comment by KirilYak** [comment]
[Lesson1-4](https://trello.com/c/F2BDYTUZ/10-lesson1-4)

**Comment by smirnovDm** [comment]
[Lesson1-2](https://trello.com/c/cx3unvbh/8-lesson1-2)

**Comment by smirnovDm** [comment]
[Lesson1-2](https://trello.com/c/cx3unvbh/8-lesson1-2)

**Pull request merged**
